steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "$_CONTAINER_REPO/$_IMAGE_NAME:code$COMMIT_SHA"
      - "-t"
      - "$_CONTAINER_REPO/$_IMAGE_NAME:latest"
      - $_ROOT_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_CONTAINER_REPO/$_IMAGE_NAME:code$COMMIT_SHA"
    id: Push
images:
  - "$_CONTAINER_REPO/$_IMAGE_NAME:code$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE_NAME: workstation-image
  _CONTAINER_REPO: europe-west1-docker.pkg.dev/mattsday-home/home
